### ISSUE TITLE
0.7.1 arm-linux-musleabi

### ISSUE THREAD

**Issue by lancethepants** [ziglang/zig-bootstrap#47]
./build -j4 arm-linux-musleabi mpcorenovfp

```
/home/user/zig-bootstrap/out/host/lib/zig/libc/musl/libc.s:3:19: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>"
.type ___environ, @object;
                  ^
```
And then it repeats this error a bunch of times with different line numbers for libc.s

I've previously built 0.7.0 fine, but I'm having this issue with 0.7.1.
I'm compiling on Debian 10.

**Comment by andrewrk** [comment]
That's unfortunately something that regressed from 0.7.0 to 0.7.1 (it occurred while fixing a different bug having to do with dynamically built musl). The fix is in zig master branch: https://github.com/ziglang/zig/commit/343249efd845c30fbdcb18a37ebb356ab19da742

I suggest to apply this patch to your local zig-bootstrap and continue with the build.

**Comment by lancethepants** [comment]
I got it to compile, thanks!  
It did take a little fiddling though.  I patched with that commit you reference, and even committed to the local bootstrap repo,  but when it does the host build part, it somehow is reverted, and requires re-patching both at original location and new host copy for it to continue.
